### ISSUE TITLE
writeFiles default should be `true`

### ISSUE THREAD

**Issue by glassdimlygr** [jeerbl/webfonts-loader#101]
Either the config examples should include `writeFiles: true` or the default should be `writeFiles: true`.

The expectation is the example configs will result in a working module, and I think you'll find that you'll get a lot more adoption of this module if you give a cut-n-paste config example that works, allowing devs to skip the RTFM and head-bang-against-wall phase of installation. 

Also, the `vusion/webfonts` `writeFiles` default is `true`, which is also confusing that the `webfonts-loader` default would be `false`.

Thank you for this code!

**Comment by jeerbl** [comment]
Hi @glassdimlygr,

There is a sample config file on the README:
![image](https://user-images.githubusercontent.com/3242928/93239008-32cd9680-f750-11ea-8b9b-f3bf39e24776.png)

About the `writeFiles` default value, I don't have time to change it right now. I can review a pull request though and push it to the registry. Keep in mind that this will be a major release.

Best,
Jerome

**Comment by jeerbl** [comment]
Although I'm wondering why it _should_ be true.

**Comment by glassdimlygr** [comment]
`writeFiles` means that files should be written to disk. That is the expectation for a working configuration. There must be some point to not writing files to disk, like in testing or something, but `writeFiles` should be the default.

Finally, yes, your screenshotted config does not include `writeFiles: true` and therefore will result in a config that does not write font files to disk in my experience and thus would appear broken / not working to the dev who installed it until they dug in and found that `writeFiles` is the `on` switch.

I think it's totally fine to just update the readme and examples to include this. I may submit a PR here for you if you're good with that solution.

**Comment by jeerbl** [comment]
I see. I got some time actually, I'll go ahead and update the code to use `writeFiles: true` as default, it will be a breaking change so it'll be in version 6.0.0.

**Comment by jeerbl** [comment]
Done in v6.0.0
