### ISSUE TITLE
writeFiles should default to false

### ISSUE THREAD

**Issue by andersk** [jeerbl/webfonts-loader#119]
Commit be4fef9b0a297c2b312adebe4575f26eb825d3c3 changed the `writeFiles` default to `true`. This creates extra unused copies of the CSS and font files in the current directory, in addition to the normal Webpack output chain. A Webpack loader shouldn’t have extra side effects like that.

**Comment by jeerbl** [comment]
@andersk you're actually entirely right. This change to use `webfonts-generator` default value was a mistake. Pull request to revert it? Actually, even having the `writeFiles` option in this webpack loader doesn't make sense. It should be false all the time.

**Comment by jeerbl** [comment]
I have to make a major version for this since it's a breaking change. Here comes v7
