### ISSUE TITLE
SASS support

### ISSUE THREAD

**Issue by romainhe** [jeerbl/webfonts-loader#129]
Hi,

Sorry if the question has already been asked but I can't find the answer anywhere... and no configuration seems to work

Currently, is there a way to export the sass file or not?

Thx for help

**Comment by romainhe** [comment]
Or is it possible to customize the generated css template, for example to add the css variables with the icon values?

**Comment by jeerbl** [comment]
@romainhe it is possible to change the css template with the `cssTemplate` option. If not provided, the [default template](https://github.com/vusion/webfonts-generator/blob/master/templates/css.hbs) will be used from `webfonts-generator`.

**Comment by romainhe** [comment]
I've done that, thank you

**Comment by groseler** [comment]
This feature as well cssDest don't seem to work.
  **scssFile: true**, option its simple ignored.
