### ISSUE TITLE
Content Hash different for same font file

### ISSUE THREAD

**Issue by scott-thrillist** [jeerbl/webfonts-loader#13]
We are on the verge of deploying a new site with this great font gen loader and we exposed a bug that may be this loader's issue or something up with webfonts-generator. Showed up during our deploy process that runs our webpack build on several servers, with our assets behind an ELB managing load.

Same version of node, shrinkwrapped npm, same exact npm list, same branch, yet we get different hashes on the woff2/woff font files, while SVG generation is identical every time. If you're running just one server this isn't an issue, but with several it becomes a blocker as all the CSS files that point to that font now have a different hash as well.

Quick fix is to force a manual cache buster like so: `"fileName": "[fontname].1.[ext]"` and just update the number manually whenever the file gets updated. Anyway, just wanted to put this on the map in case anyone else is suffering from the same issue.

**Comment by jeerbl** [comment]
Sorry I didn't have time to look at this before. I'll try to find the time soon :)

**Comment by jeerbl** [comment]
Should be fixed in 2.0.0!

**Comment by scott-thrillist** [comment]
I'm in the process of updating our setup from webpack 2 -> 3. Will definitely add this in, thanks

**Comment by scott-thrillist** [comment]
Just an update, this doesn't appear to be fixed. Had the same issue in a production deploy and had to roll back :x 

I'm back to doing the update method listed above. Just an update for anyone else having the same issue

**Comment by jeerbl** [comment]
Hi @scott-thrillist!

Do you use `[chunkhash]` instead of `[hash]` for the file name? `chunkhash` is built using the hash of every SVG in your font so it shouldn't change from a build to another.

Cheers
Jerome

**Comment by scott-thrillist** [comment]
Totally my fault and I caught this right after my post. Currently in testing

**Comment by jeerbl** [comment]
Sure! I'll close the issue, don't hesitate to comment back when you have your tests results.
