### ISSUE TITLE
scssFile and cssDest options are simply being ignored.

### ISSUE THREAD

**Issue by groseler** [jeerbl/webfonts-loader#132]
scssFile and cssDest options simply being ignored. Am I missing something?

**My config.font.js**
`module.exports = {
  files: [
    '../svg/*.svg'
  ],
  fontName: 'pois',
  classPrefix: 'pois-',
  baseSelector: '.pois',
  types: ['eot', 'woff', 'woff2', 'ttf', 'svg'],
  fixedWidth: true,
  fileName: 'fonts/[fontname].[chunkhash].[ext]',
  scssFile: true,
  cssDest: './fonts/scss/_icons.scss',
};`

Thank you

**Comment by antipenko** [comment]
Hey, @groseler ! did you manage to solve this problem?
