### ISSUE TITLE
Exported Codepoints/SCSS Ignore startCodepoint Setting/emitCodepoints Values

### ISSUE THREAD

**Issue by rshelnutt** [jeerbl/webfonts-loader#134]
Experiencing an issue using the latest build. Trying to hard-set the codepoints so they don't keep changing when new icons are added - icons are being used on several pseudo elements in builds and need to be statically defined.

I'm using the `startCodepoint` option in the font configuration to try and combat this, but the option appears to be completely ignored in both the codepoint export _and_ the generated CSS/SCSS. When exporting the codepoints to json (and all other formats), they appear to be starting at `61697` regardless of the `startCodepoint` override setting, then proceeding upwards. Possible that this may be related to the cause of the issue on #53?

**Option Setting**
```javascript
startCodepoint: Number('0xe900')
```

**Expected Codepoint Behavior**
```json
{
    "icon-alert": e900,
    "icon-arrow-down": e901,
    "icon-arrow-left": e902,
    "icon-arrow-right": e903,
    "icon-arrow-up": e904
}
```

**Exported Codepoints**
```json
{
    "icon-alert": 61697,
    "icon-arrow-down": 61698,
    "icon-arrow-left": 61699,
    "icon-arrow-right": 61700,
    "icon-arrow-up": 61701
}
```

**Generated Styles**
```css
.icon-alert:before {
  content: "\F101";
}

.icon-arrow-down:before {
  content: "\F102";
}

.icon-arrow-left:before {
  content: "\F103";
}

.icon-arrow-right:before {
  content: "\F104";
}

.icon-arrow-up:before {
  content: "\F105";
}
```

Using Laravel Mix, but defined webpack settings are the same. Not experiencing any issues with build, frontend display (when using exported classes) or anything else.

**Webpack Config**
```javascript
module: {
  rules: [
    {
      test: /\.font\.js/,
      use: [
        MiniCssExtractPlugin.loader,
        {
          loader: 'css-loader',
          options: {
            url: false
          }
        },
        {
          loader: 'webfonts-loader'
        }
      ]
    }
  ]
}
```

**Font Config**
```javascript
module.exports = {
  'files': [
    './icons/*.svg'
  ],
  fontName: 'thefont',
  publicPath: '/',
  classPrefix: '',
  baseSelector: '.icon',
  types: ['woff'],
  fixedWidth: false,
  normalize: true,
  fileName: '[fontname].[hash].[ext]',
  embed: false,
  scssFile: true,
  startCodepoint: Number('0xe900'),
  emitCodepoints: { fileName: '[fontname].codepoints.fonts.js', type: 'json' }
}
```

Thank you for all your hard work - this has been amazing to use and has been my favorite package as of late. Any assistance or insight you can provide would be greatly appreciated.

**Comment by andreicnegrea** [comment]
@rshelnutt It looks like that webfonts-generator startCodepoint setting is not exposed, and that's the reason your override never works. I agree that exposing startCodepoint would be a nice-to-have.

**Comment by rshelnutt** [comment]
@andreicnegrea I see; I think a solid argument exists that would make that functionality essential in several projects - especially for use in CSS pseudo classes. The **emitCodepoints** functionality _does_ seem to be supported however, and (unless I'm missing something) still seems to be publishing erroneous values irreverent to the default codepoints being used.

It wouldn't be much of an issue if there were a cached index of the generated codepoints expanded with each new icon vs resetting every codepoint after the new icon's alphabetic placement.

**Comment by jeerbl** [comment]
Hi @rshelnutt,

As @andreicnegrea said, the `startCodepoint` option of `webfonts-generator` is not currently exposed. Maybe you could provide a pull request exposing that option? Kind of busy at the moment, I wouldn't have the time really.

Much appreciated guys!

Jerome
