### ISSUE TITLE
Override icons with the same name

### ISSUE THREAD

**Issue by bitwikinger** [jeerbl/webfonts-loader#136]
I am loading SVG from 2 different folders. In these folders are SVGs with different names and some with the same name. Webpack throws an error: `Error: The glyph name "foo" must be unique.`
Is there any way that I can tell the loader to override icons with the same name?

``` 
module.exports = {
  files: ['./folder1/*.svg', '../../folder2/*.svg'],
  fontName: 'my-icons',
  classPrefix: 'my-',
  baseSelector: '.myicon',
  types: ['woff2'],
  fileName: 'my.[fontname].[hash:6].[ext]',
}
```

**Comment by scheijan** [comment]
I was trying to do the same thing and ran into the same problem - is there any way to override icons with the same name?

**Comment by jeerbl** [comment]
@bitwikinger why not renaming them yourself? That'd be weird having such an option on the loader, why not have a script merging directories beforehand, with your own overwrite policy?

I don't think I'll add that functionality. I suggest you make the directories clean beforehand.

Closing as won't fix.
