### ISSUE TITLE
SVG icon has different color, the generated iconfont only monochrome ?

### ISSUE THREAD

**Issue by jiechud** [jeerbl/webfonts-loader#14]
I have a color.svg files

![qq 20170406170348](https://cloud.githubusercontent.com/assets/9709396/24746309/4287cc66-1aeb-11e7-8095-c51fb0350820.png)

Iconfont after conversion

![t](https://cloud.githubusercontent.com/assets/9709396/24746384/7d3cf264-1aeb-11e7-86a5-68d8c2f72365.png)

Could not find options can be set up

**Comment by jeerbl** [comment]
Hi @jiechud!
Thing is, it is a font and a font has no _color_, only the one you give them! Let's say the well-known Arial font for example, when you write in your CSS `color: black` the text will be displayed black, you can't add other colors. Just like the font you generated.

Cheers,
Jerome
