### ISSUE TITLE
Security issue: Misinterpretation of malicious XML input  

### ISSUE THREAD

**Issue by mzabuawala** [jeerbl/webfonts-loader#143]
<img width="806" alt="Screenshot 2021-08-09 at 11 59 22 AM" src="https://user-images.githubusercontent.com/19573369/128667651-514f8bab-073f-4592-89de-686e0318dfc3.png">

`

**Comment by Eusebius1920** [comment]
This seems to be an issue of `@vusion/webfonts-generator`, which depends on `svg2ttf@5` and had to update to `svg2ttf@6`

**Comment by Eusebius1920** [comment]
Even `svg2ttf@6` does use `xmldom ~0.6.0`. So they have to update to xmldom `>= 0.7.0` too.
