### ISSUE TITLE
Probably lost support for SCSS files inclusion/variables

### ISSUE THREAD

**Issue by cuchac** [jeerbl/webfonts-loader#145]
Hello,
I totally agree with #119 that loader should not produce random files in dist folder and using `generateCss()` is much much cleaner. But it broke scss file use-case.

I have quite common use-case of generating SCSS file with code-points variables and using such variables in standard scss files. So what I need is to include generated SCSS file in other SCSS file to get codepoint variables defined. I was trying for several hours and failed. I ended with hack that is working but is very ugly - using second entry for generating scss file and storing generated scss in `something.scss` file and including that file again in another entry. I can post example, if someone wants to.

I think there should be cleaner way to include generated scss in another scss file. Don't you know the correct way? Something like `@import 'something.font.js';` but it does not work. Sass is importing js file, not generated scss.

**Comment by jeerbl** [comment]
Hello @cuchac, possible to make a PR if you've got a solution?
