### ISSUE TITLE
There's no option for "@font-face only"

### ISSUE THREAD

**Issue by lazytyper** [jeerbl/webfonts-loader#146]
The big advantage of ligatures is:

The icon names are already present in the fonts. There is no longer need to create a CSS rule for each icon.

I couldn't find an option for turning off creating those rules and create just the `@font-face` specification and the fonts.

**Comment by lazytyper** [comment]
The webfonts-generator which is used, doesn't support that feature either. So, there's no way to disable creating icon classes.

**Comment by jeerbl** [comment]
Closing as `webfonts-generator` doesn't include that feature yet.
