### ISSUE TITLE
writeUint32LE is not function

### ISSUE THREAD

**Issue by WuQiuYang** [jeerbl/webfonts-loader#167]
![c15d7efaa810235dbc998b2764767014](https://user-images.githubusercontent.com/38161177/163596092-aaff5494-c228-4148-af17-467a1abfbda3.png)

env:

node v12.16.1
node-gyp -v v5.0.5
Linux 3.10.0-862.el7.x86_64

**Comment by WuQiuYang** [comment]
7.5.0

**Comment by CharlesPhonepraseuth** [comment]
Try to update node, I had the same bug, I fixed it by update node from 12.18.3 to 16.14.2

**Comment by jeerbl** [comment]
@WuQiuYang closing the issue as it is related to the Node version you're using. Feel free to reopen if ever
