### ISSUE TITLE
Webpack 2 config documentation

### ISSUE THREAD

**Issue by Dharmoslap** [jeerbl/webfonts-loader#17]
Please add documentation about how to setup this in Webpack 2 config file.

**Comment by Dharmoslap** [comment]
Is this actually supposed to work with webpack2 already?

**Comment by jeerbl** [comment]
Yes I use it with Webpack 2 myself.

**Comment by Dharmoslap** [comment]
Hehe, then you can just copy paste the config to README.

**Comment by jeerbl** [comment]
I'll copy paste here, will do it on README when home:

```javascript
{
    test: /\.font\.json/,
    use: [
        'style-loader',
        'css-loader?-autoprefixer',
        'postcss-loader',
        'webfonts-loader'
    ]
}
```

Does that answer your question?

**Comment by Dharmoslap** [comment]
It does, indeed working now.

**Comment by FinesseRus** [comment]
@jeerbl `postcss-loader` is not required in [your example](https://github.com/jeerbl/webfonts-loader/issues/17#issuecomment-297980528)

**Comment by jeerbl** [comment]
@FinesseRus indeed it is not ;). I use `autoprefixer` with my config instead of `autoprefixer` from the `css-loader`, that's why.

I updated the example.
