### ISSUE TITLE
How can this be configured for SASS and webpack2?

### ISSUE THREAD

**Issue by fago** [jeerbl/webfonts-loader#18]
I've got a webpack2 config like
```
      // Add support for icon fonts.
      {
        test: /\.font\.js/,
        exclude: ['node_modules', 'bower_components'],
        loader: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: [
          'css-loader?importLoaders=1',
          'webfonts-loader'
        ]
      })
      }
```
and configured the generate to use the scss template. However, that way the sass mixins end up in my applications css file. How is that configured, such that I can use the generated mixin in my sass?

**Comment by jeerbl** [comment]
I take this as part of #17. There should be better documentation, I will do it as soon as I can.

**Comment by fago** [comment]
ok, thank you!
