### ISSUE TITLE
Extract text plugin

### ISSUE THREAD

**Issue by demyan1411** [jeerbl/webfonts-loader#20]
Hello,
Haw can i integrate Extract text plugin
I tried do something like this:
`loader: ExtractTextPlugin.extract({
            fallback: 'style-loader',
            use: ['css-loader?-autoprefixer', 'postcss-loader', 'webfonts-loader']
        })`

but it no working

**Comment by jeerbl** [comment]
This is what I do on my side:
```
{
    test: /\.font\.json/,
    loader: ExtractTextPlugin.extract({
        use: [
            'css-loader?-autoprefixer',
            'postcss-loader',
            'webfonts-loader'
        ]
    })
}
```

**Comment by demyan1411** [comment]
in my main.js
`import './font_icons.font';`

in font_icons.font.json

```
{
    "files": ["../images/icons/*.svg"],
    "fontName": "Awesomecons",
    "classPrefix": "ai-",
    "baseSelector": ".ai",
    "fixedWidth": true,
    "types": ["eot", "woff", "ttf", "svg"],
    "fileName": "fonts/[fontname].[ext]",
    "cssFontsPath": "../"
}
```

in webpack.config
```
{
            test: /\.font\.json/,
            include: /node_modules/,
            loader: ExtractTextPlugin.extract({
                fallback: 'style-loader',
                use: [
                    'css-loader?-autoprefixer',
                    'postcss-loader',
                    'webfonts-loader'
                ]
            })
        }
```

and it is not working =(((

**Comment by jeerbl** [comment]
Are you sure your json file passes through the loader?

**Comment by demyan1411** [comment]
I think so

**Comment by demyan1411** [comment]
If I do without ExtractTextPlugin
```
test: /\.font\.js/,
loaders: ['style-loader', 'css-loader?-autoprefixer', 'postcss-loader', 'webfonts-loader']
```

It is work, but I need extract =(

**Comment by jeerbl** [comment]
Does ExtractTextPlugin work for other files? Or is it just the webfonts loader?

**Comment by shafqatdotnet** [comment]
Here is what i did for my project (webpack2) and its working:
//My icons.fonts (in the same folder where my SVGs are):
`module.exports = {
  "files": [   
    "*.svg"  
  ],
  "fileName": "content/styles/fonts/CostarIconsFont.[ext]",
  "fontName": "CostarIconsFont",   
  "fixedWidth": true,  
  "types": ["eot", "woff","woff2", "ttf", "svg"]  
}`

Webpack.config.js:
`{
                test: /.*\.fonts/,
                //enforce:'pre',
                exclude: /(node_modules|dist)/,
                use: ExtractTextPlugin.extract({
                    use: [
                        {
                            loader: "css-loader",
                            options: {
                            }
                        },
                        {
                            loader: "webfonts-loader?embed",
                            options: {
                            }
                        }
                    ]
                })
            },`
