### ISSUE TITLE
How would one generate SASS instead of CSS?

### ISSUE THREAD

**Issue by fago** [jeerbl/webfonts-loader#21]
As noted in #18 it's unclear to me how this is supposed to be used with sass. The configuration in #17 does not help me - I got it working with webpack2 in general, but I do not know how to integrate it into my sass workflow. By default it did generate CSS, but that way the icon font cannot be used in the sass files. So I tried changing the template to the scss template as that seems to generate useful scss mixins. Can they be used somehow? Or is there some other way to use this with sass mixins?

**Comment by jeerbl** [comment]
Indeed. I use `webfonts-generator` under the hood and there is an option for SASS template as you can see [here](https://github.com/sunflowerdeath/webfonts-generator#csstemplate). I will integrate this in the next release.

**Comment by jantimon** [comment]
Please take a look at https://github.com/jantimon/iconfont-webpack-plugin it does it a little bit different but works great with sass :)

**Comment by Rzial** [comment]
Hi! Something new on this?

I'm interested in this package but I use SASS in my setup :(

**Comment by yohannprigent** [comment]
This would be awesome to have SASS support!

**Comment by jantimon** [comment]
Any reason you deleted my comment?
I was just interested about feedback to my loader which supports sass.

**Comment by jeerbl** [comment]
@jantimon no offense here, your comment added no value to the issue here, that's why I deleted it. I am more than happy if you want to help on this project ;)

**Comment by jantimon** [comment]
I am always happy to help.  
Actually both loaders do almost the same thing - just with different approaches.  
The **webfonts-loader follows the best practices** how font used to be integrate for years.  
The [iconfont-webpack-plugin](https://github.com/jantimon/iconfont-webpack-plugin) tries a different approach: it uses postcss ast together with webpack resolving, webpack file watching and webpack caching and is therefore compatible with less, sass, scss, stylus and vanilla css.  
It also removed obsolete fonts like `ttf` or `eot` as they aren't needed for modern browsers anymore: 
[![can_i_use_woff](https://user-images.githubusercontent.com/4113649/29276285-61bb8666-810e-11e7-9cbc-581efee397dd.jpg)](http://caniuse.com/woff/embed)
But still I would like to know what disadvantages you see compared to webfonts-loader

**Comment by jeerbl** [comment]
I investigated a bit and opened [this issue](https://github.com/shakacode/sass-resources-loader/issues/48) on the `sass-resources-loader` package. I'll update this issue with any further development. So for now, SASS is not supported. Hope I'll get it working soon.

I'll keep you guys updated!

Cheers
Jerome

**Comment by airtonix** [comment]
@jantimon `iconfont-webpack-plugin` also doesn't work for people using sass. due to how sass tries to resolve the `url()` value.

**Comment by jeerbl** [comment]
SASS generation won't be supported in `webfonts-loader` for the time being as I can't find a viable solution to handle this.

Magic PRs allowing this welcome.
