### ISSUE TITLE
Working demo?

### ISSUE THREAD

**Issue by opendnb** [jeerbl/webfonts-loader#22]
Hi. 

Are you able to provide a full working demo with config pleeeeease... I can't get this working no matter what i try

Thanks

**Comment by jeerbl** [comment]
Hi!

Are you using Webpack 1 or Webpack 2? I am a bit in a rush right now (just moved far away ^^) so I'll do my best to assist you :).

Cheers,
Jerome

**Comment by jeerbl** [comment]
Hi!

A working demo can be found in the test directory. I rewrote the README as well so that it is easier to understand how to make it work.

Thanks!
Jerome
