### ISSUE TITLE
Default publicPath value, relative publicPath

### ISSUE THREAD

**Issue by saskodh** [jeerbl/webfonts-loader#28]
Hi,
thanks for writing this loader. It integrates nicely in our Webpack configuration.
However I've noticed a small issue connected with the default value of the publicPath.

According to the Webpack [docs ](https://webpack.js.org/configuration/output/#output-publicpath) the default value for publicPath is an empty string, which means relative to the page. This is the case in my app and in the production build I omit defining the publicPath. When using this loader in the urls for the font I have absolute url (starting with /). I suppose the issue is on this [line](https://github.com/jeerbl/webfonts-loader/blob/master/index.js#L152).

Note: If the path is relative in the urls for the fonts, through the css-loader, Webpack will require the file and fail because the file does not exists. Any ideas on how we can fix this?

**Comment by erwingo** [comment]
I'm having the same issue, if the `output.publicPath` option is omitted or an empty string, I expect all my urls to resolve in "relative" way. However, this loader prefixes the font urls with `/`

**Comment by saskodh** [comment]
@erwingo, I found a temporary workaround for this. It might helpful also for you.
- set publicPath='./'
- disable url requires for the css-loader: { loader: 'css-loader', options: { url: false } }

**Comment by erwingo** [comment]
@saskodh thank you! I tried with that publicPath but what was missing was the css-loader config.
