### ISSUE TITLE
Set style-loader as fallback

### ISSUE THREAD

**Issue by gvonem** [jeerbl/webfonts-loader#30]
Hi there,

when set up my webpack.config.js like its documented in the readme, i got errors - so, instead of:
```
use: [
      'style-loader',
      'css-loader',
      'webfonts-loader'
    ]
```
i did:
```
use: [
      'css-loader',
      'webfonts-loader'
    ],
fallback: "style-loader"
```
and it's working fine. :relaxed:

**Comment by jeerbl** [comment]
Hi!

What error do you get? In my tests I add `style-loader` after `css-loader` and it is working fine. Did you install `style-loader`?

Thanks
Jerome

**Comment by vlmonk** [comment]
Hi. Have this issue too. Seen message `Module build failed: ReferenceError: window is not defined` with config from example.

https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/503#issuecomment-320735068

**Comment by gvonem** [comment]
Like vlmonk said:
```
ERROR in ./src/scripts/myfont.font.js
Module build failed: ReferenceError: window is not defined
```
Plus a lot of paths i'd put into a file, if you want to look at it.

**Comment by jeerbl** [comment]
Hey @gvonem! Did the issue persist? If yes, I would be more than happy to see your logs or whatever you can give me so that I can investigate this.

**Comment by thanosasimo** [comment]
Same issue here!
Following the docs i get an error
`ERROR in ./src/icons/icons.font.js
Module build failed: ReferenceError: window is not defined`
I am using:
"webpack": "^4.6.0",
"style-loader": "^0.21.0",
"css-loader": "^0.28.11",
"webfonts-loader": "^4.1.0"

**Comment by jeerbl** [comment]
The issue came from the fact that `style-loader` is trying to inject the style inline but `ExtractTextPlugin` is trying to extract the CSS in a separate CSS file. Either you use `style-loader` for inline style or `ExtractTextPlugin` for a separate CSS file.

See [this issue](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/503#issuecomment-320735068) for more details.
