### ISSUE TITLE
Passing custom options.dest emits file named "undefined"

### ISSUE THREAD

**Issue by IlyaSemenov** [jeerbl/webfonts-loader#36]
## Steps to reproduce

Pass `options.dest` to the loader:

```js
...
{
  test: /\.font\.(js|json)$/,
  loader: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      'css-loader',
      {loader: 'webfonts-loader', options: {dest: '/min/'}}
    ]
  })
},
```

## Expected result

The generated URLs in CSS start with `/min/`, in full accordance to the code:

```js
  var pub = (
    generatorConfiguration.dest || (opts.output && opts.output.publicPath) || '/'
  );
```

## Actual result

The URLs actually start with `/min/`, but all generated fonts are saved to the file named `undefined` (literally):

![screen shot 2017-09-27 at 15 11 44](https://user-images.githubusercontent.com/128121/30902883-20f29a06-a397-11e7-9890-6ab4aa5ea67c.png)

There is clearly a bug in the logic, because if there is a custom `dest`, you call `emitFile` referring to non-existent data:

<img width="637" alt="screen shot 2017-09-27 at 15 19 24" src="https://user-images.githubusercontent.com/128121/30903029-9c676400-a397-11e7-8937-553254268155.png">

## Why this is important

With default settings, the generated CSS looks like this:

```css
...
url("/23aba34a4572f7baa0aa-icons.woff") format("woff"),
```

This is unusable, because the assets typically do NOT reside directly at the site root. They normally reside under `/static/` or `https://static.project.net/`, and there must be a way to tell `webfonts-loader` to emit proper working URLs.

Ideally, `webfonts-loader` should pick `webpackConfig.output.publicPath` automatically, without any additional setup. I can see that there is code that attempts to do so, but it uses legacy webpack 1.x API, and does nothing in Webpack 2.x and 3.x (unless `LoaderOptionsPlugin` is used).

**Comment by IlyaSemenov** [comment]
I think I mistreated `options.dest` as the URL prefix. It is passed verbatim to `webfontsGenerator(options)` so obviously it can't be a URL. But then how come it is assigned to `pub` and used to construct URL later on? The whole stuff seems to be broken for that matter. 

There should be `options.dest` and `options.publicPath`, handled independently.

**Comment by jeerbl** [comment]
Hi!

Thanks for opening the issue. I will take a look at the PR bu it definitely seems legit.

Cheer
Jerome
