### ISSUE TITLE
Relative Paths for URLs

### ISSUE THREAD

**Issue by darylteo** [jeerbl/webfonts-loader#39]
Hi @jeerbl thanks for continuing to maintain this library! Pity the MIT licensing is causing issues with merging into webpack-contrib... hope that gets sorted out eventually as this is a critical plugin.

I have a hack in place for fontgen-loader, but I did create a issue for it in the old project

https://github.com/DragonsInn/fontgen-loader/issues/30

Hopefully you will have something for this =)

Regards,
Daryl

**Comment by jeerbl** [comment]
Is it working with v4?
