### ISSUE TITLE
Suggestion: Add 'limit' option similar to url-loader

### ISSUE THREAD

**Issue by Freywar** [jeerbl/webfonts-loader#42]
Currently there's similar `embed` flag to check if we want to include font data as a Base64 string to emitted CSS module. It makes us to manually track emitted font files sizes as we add or remove icons and switch the flag when the files are too big/small to be embedded/have a separate HTTP request. `limit` parameter would allow to configure it once and let the loader to decide whether to embed or not automatically.

Also currently it's not possible to i. e. embed most used format to reduce bundle size and preserve others as separate files loaded on demand. Even better solution would be to somehow push emitted font files into normal webpack flow and let it use the same loaders as for other font files.

**Comment by jeerbl** [comment]
Regarding your second point, you can always tell Webpack how to load the emitted font files, just specify their format and specify the loaders that should handle them in your Webpack config.

Regarding the limit, I don't think it should be up to the plugin to decide whether or not it is too big or too small. Webpack now tells you which emitted files are considered too big in the build info and it should be up to the developer to handle performance-related issues.
