### ISSUE TITLE
Not exporting CSS

### ISSUE THREAD

**Issue by thiagocoelho** [jeerbl/webfonts-loader#47]
Hello guys,

I'm trying to find out why my css font isnt being extracted!

The build is working great, my fonts are being generated but not the css, I'm really frustrated, I've read the docs 10 times, trying different configurations, almost giving up.

Here is my webpack config:

```
const path = require('path');
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
const CleanWebpackPlugin = require('clean-webpack-plugin');
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');

const is_production = process.env.NODE_ENV;

let appEntry = [
  'react-hot-loader/patch',
  'webpack-dev-server/client?http://localhost:8080',
  'webpack/hot/only-dev-server',
  './src/index.js'
];

if (is_production) {
  appEntry = ['./src/index.js'];
}

let config = {
  entry: {
    app: appEntry,
    vendors: [
      'script-loader!./src/vendors/olosws.js',
      'script-loader!./src/vendors/olos_cti.js'
    ]
  },
  output: {
    filename: '[name].js',
    path: path.resolve(__dirname, 'dist'),
    publicPath: ''
  },
  devtool: is_production ? '' : 'source-map',
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        use: 'babel-loader',
        exclude: [
          /node_modules/
        ]
      },
      {
        test: /\.(scss|css)$/,
        use: [
          'style-loader', 
          {
            loader: 'css-loader',
            options: {
              modules: false,
              importLoaders: 1,
              sourceMap: true
            }
          }, 
          'group-css-media-queries-loader',
          'resolve-url-loader',
          'sass-loader?sourceMap'
        ]
      },
      {
        test: /\.font\.js/,
        loader: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            {
              loader: 'css-loader',
              options: { url: false }
            },
            {
              loader: 'webfonts-loader',
              options: { publicPath: '.' }
            }
          ]
        })
      },
      {
        test: /\.(png|jpg|gif)$/,
        use: [{
          loader: 'file-loader',
          options: {
            name: '[name].[ext]',
            outputPath: 'images/'
          }
        }],
      }
    ],
  },
  plugins: [
    new webpack.NamedModulesPlugin(),
    new ExtractTextPlugin({
      filename:'[name].css', 
    })
  ],
  resolve: {
    extensions: ['.js', '.jsx'],
    alias: {
      assets: path.resolve(__dirname, './src/assets/')
    }
  }
};

if (is_production) {
  config.plugins.push(
    new UglifyJSPlugin(),
    new BundleAnalyzerPlugin(),
    new webpack.DefinePlugin({
      'process.env': {
        'NODE_ENV': JSON.stringify('production')
      }
    })
  );
} else {
    config.devServer = {
      compress: true,
      contentBase: path.resolve(__dirname, 'dist'),
      hot: true,
      historyApiFallback: true,
      publicPath: '/'
    };
    config.plugins.push(new webpack.HotModuleReplacementPlugin());
}

module.exports = config;
```

Font config:

```
module.exports = {
  'files': [
    './assets/icons/*.svg'
  ],
  'fontName': 'eaglleicons',
  'classPrefix': 'icon-',
  'baseSelector': '.icon',
  'types': ['woff2', 'ttf'],
  'fileName': './fonts/[fontname].[ext]'
};
```

I put the require of font config in my `index.js`.

Any ideia of what I'm missing? I know that github isn't a support plataform but following the docs I'm not getting the desired results, sorry for any incovenience.

**Comment by SouroucheB** [comment]
I'm experimenting the exact same issue and the exact same frustration. I can not figure out how to access my icons through my react app ! The worst is that you asked your question almost 2 months ago and nobody has given you an answer !

**Comment by SouroucheB** [comment]
I've founded a way :
`.addLoader({
    test: /\.font\.js/,
    loader: ExtractTextPlugin.extract({
      fallback: 'style-loader',
      use: [
        'css-loader?importLoaders=1',
        'webfonts-loader',
      ],
    }),
  })`
and :
`const path = require('path');

module.exports = {
  files: ['./assets/fonts/*.svg'],
  fontName: 'myfonticons',
  classPrefix: 'myfonticon-',
  baseSelector: '.myfonticon',
  cssTemplate: path.resolve('node_modules/webfonts-generator/templates/css.hbs'),
  types: ['eot', 'woff', 'woff2', 'ttf', 'svg'],
  fileName: 'app.[fontname].[hash].[ext]',
  embed: true,
};
`

**Comment by bbugh** [comment]
@SouroucheB can you post your whole webpack config?

**Comment by mrzdevcore** [comment]
Did anyone tried it on webpack 4 ? I have the same issue also.

**Comment by bbugh** [comment]
I'm on Webpack 4 as well, and since ExtractTextPlugin is soft deprecated with WP4 I figured that was part of the problem.

I spent several hours trying to get every font generation package I could find working until landing on 
https://www.npmjs.com/package/iconfont-webpack-plugin. It worked out of the box without a bunch of shenanigans, and it was coincidentally my favorite API, very simple. It adds a custom postcss loader and a custom `font-icon` css property, then turns them all into a font. Here's my setup for it: https://gist.github.com/bbugh/bcc14a4e9266a5e6578c849b39f35dcd

**Comment by jeerbl** [comment]
Tried with Webpack 4 and it works fine with me, look at the tests in the repo, it might be of help ;)

**Comment by YonathanB** [comment]
It doesn't downloading the fonts.
I can see the css files with my desired configuration, but fonts aren't downloaded. 
In html I have a little square.

Any help?

**Comment by jeerbl** [comment]
Closing cause inactivity
