### ISSUE TITLE
Segmentation faul

### ISSUE THREAD

**Issue by jiechud** [jeerbl/webfonts-loader#5]
‘Segmentation faul’t occurs when webpack is packaged

error info
 npm/webpack: line 14:  4696 Segmentation fault      node "$basedir/node_modules/webpack/bin/webpack.js" "$@"

**Comment by jeerbl** [comment]
What's in your configuration? Are you sure this is not related to some misconfiguration?

**Comment by jiechud** [comment]
@jeerbl  my configuration

 webpack.config.js
```
'use strict';
let debug = process.env.NODE_ENV !== "production";
let path = require('path');
let webpack = require('webpack');

// GLOBALS
let GlobalPlugin = new webpack.DefinePlugin({
    DEBUG: debug
});

module.exports = {
    context: path.join(__dirname, "src"),
    entry: [
        './index'
    ],
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'bundle.js',
        publicPath: '/dist/'
    },
    module: {
        loaders: [{
            test: /\.js$/,
            loader: 'babel',
            exclude: /(node_modules|bower_components)/,
            query: {
                presets: ['es2015', 'react', 'stage-0']
            },
            include: __dirname
        }, {
            test: /\.font\.(js|json)$/,
            loaders: ['style-loader', 'css-loader', 'webfonts-loader']
        },
        {
            test: /\.(woff|eot|ttf|svg)$/,
            loader: 'url-loader'
        }]
    },
    plugins: [
        GlobalPlugin
    ],
    resolve: {
        root: path.join(__dirname, 'src')
    }
}

```
module
```
module.exports = {
  fontName: 'Octicons',
  files: [
    "./src/icons/close.svg"
  ],
  baseClass: 'octicon',
  classPrefix: 'octicon-'
};
```

**Comment by jeerbl** [comment]
And if you remove the loader for the font, you get the same error?

**Comment by jiechud** [comment]
If remove webfonts-loader was no problem, I use webfonts-loader provide the test also can appear this problem, but not every time.  
My version if there is a problem ?
node : v5.7.1  npm: v3.6.0

**Comment by jeerbl** [comment]
Well I don't see anything wrong in your configuration. Did you try debugging it? I can't reproduce it on my side.

Maybe it is related to your `resolve.root` config? I see the files path in the font config starts with `src` but `src` is configured to be the root of your project. Try to remove `src` from the files paths in your font config.

**Comment by jiechud** [comment]
I put the node to upgrade to the latest version, this problem won't occur

**Comment by jeerbl** [comment]
Is the issue still occuring?

**Comment by jiechud** [comment]
isuse resolved ，Thanks
