### ISSUE TITLE
Any chance to support multicolored icons?

### ISSUE THREAD

**Issue by nelsieborja** [jeerbl/webfonts-loader#50]
This plugin is very helpful for us in generating icon fonts from SVG for our project, and very hopeful we could still do. Would there be any chance you'll be extending the feature of this plugin to support multicolored icons? Thanks in advance! :)

**Comment by jeerbl** [comment]
Hi @nelsieborja !

As you noticed, this plugin generates fonts (such as Arial or Times New Roman), meaning it defines only the shapes and not their colors, just like any font. It is therefore impossible to support multicolor icons as we're not talking about icons in the end, but fonts.

Thanks,
Jerome
