### ISSUE TITLE
Question: Can publicPath be set to './' in the generated file?

### ISSUE THREAD

**Issue by abhishekdev** [jeerbl/webfonts-loader#52]
**Description**
In a scenario where I am generating a CSS library and using font icons as a fallback, could I set the font-face paths to be a relative path in the generated file?

This way the CSS lib would load the files irrespective of the domain its injected into.

**What I have tried**
I have tried the suggestions in #28, but that does not seem to alter the output path with the current version.

**Additional Info**
Unless I am missing something, I guess the usage of nodejs `url.resolve` on this [line](https://github.com/jeerbl/webfonts-loader/blob/59a96f26c6ca347005f6abbd8599847c667354d2/index.js#L176) would discard the relative paths in most scenarios. 

```node
> url.resolve('/','/iconpath')
'/iconpath' // path discarded 
> url.resolve('./','/iconpath')
'/iconpath' // path discarded 
> url.resolve('./','iconpath')
'iconpath' // path discarded 
> url.resolve('https://example.com','/iconpath')
'https://example.com/iconpath' // path kept
```

**Comment by jeerbl** [comment]
@abhishekdev I made some updates. By the way could you tell me which version of Webpack you are using? Thx

**Comment by abhishekdev** [comment]
I am using `webpack: ^3.12.0`.

Thanks for the nudge. I see your updates to the project since this issue was filed...I will try the latest.

**Comment by abhishekdev** [comment]
I can confirm this issue still exists with:

```
 "webfonts-loader": "^4.4.0",
 "webpack": "^4.28.4",
```

The only workaround for now is to have the CSS file and the fonts remain in the same directory.

PS: Sorry for such a late update form my end; the latest version update brought this back to my radar.

**Comment by Finesse** [comment]
I have the same problem. I need to make a CSS file that loads font files from a path relative to the CSS file, e.g. `../fonts/myfont.woff` (because the page URL and the site root are not known beforehand). I tried everything and every time the font URL was `/fonts/myfont.woff`.

**Comment by xingxiuyi** [comment]
try this:

```javascript
    output: {
        publicPath: './',
    },
    module: {
        rules: [
            {
                test: /\.font\.js/,
                use: [
                    MiniCssExtractPlugin.loader,
                    {loader: 'css-loader', options: {url: false,}},
                    {
                        loader: 'webfonts-loader',
                        options: {
                            'publicPath': './',
                        }
                    }
                ]
            }
        ]
    },
```

ensure extract css has relative url, and disable `css-loader` url resolving for relative URLs. 

generated css like

```css
@font-face {
    font-family: "my-font-icon";
    src: url("my-font-icon.woff2") format("woff2"),
    url("my-font-icon.woff") format("woff");
}
```

**Comment by abhishekdev** [comment]
@xingxiuyi I can confirm, that this approach does work with webpack 4.29.5 and webfonts-loader 4.4.0. Thanks for sharing 👍

**Comment by peiris** [comment]
> try this:
> 
> ```js
>     output: {
>         publicPath: './',
>     },
>     module: {
>         rules: [
>             {
>                 test: /\.font\.js/,
>                 use: [
>                     MiniCssExtractPlugin.loader,
>                     {loader: 'css-loader', options: {url: false,}},
>                     {
>                         loader: 'webfonts-loader',
>                         options: {
>                             'publicPath': './',
>                         }
>                     }
>                 ]
>             }
>         ]
>     },
> ```
> 
> ensure extract css has relative url, and disable `css-loader` url resolving for relative URLs.
> 
> generated css like
> 
> ```css
> @font-face {
>     font-family: "my-font-icon";
>     src: url("my-font-icon.woff2") format("woff2"),
>     url("my-font-icon.woff") format("woff");
> }
> ```

Thanks mate. saved my day!
