### ISSUE TITLE
Usage with nuxt

### ISSUE THREAD

**Issue by sourenaraya** [jeerbl/webfonts-loader#58]
Any idea how to use this with nuxt.js?

**Comment by jeerbl** [comment]
Well, what did you try?

**Comment by KRaymundus** [comment]
Couldn't get this to work either. 
What I did: 
1. Create a nuxt app with vuetify like here: https://github.com/nuxt/create-nuxt-app
2. Add to package.json: "webfonts-loader": "^4.3.0" and run npm install
3. In nuxt-config.js add `~/plugins/icons` to the plugins array
4. In nuxt-config.js at the build section add:
```
extend(config, ctx) {
  config.module.rules.push({
    test: /plugins\/icons\.js$/,
    use: ['vue-style-loader', 'css-loader', 'webfonts-loader'],
  })
}
```
5. In the plugins folder, add a file icons.js
```
module.exports = {
  files: ['../assets/icons/*.svg'],
  fontName: 'TopLoggerIcons',
  classPrefix: 'tl-',
  baseSelector: '.tl',
  types: ['eot', 'woff'],
  fixedWidth: true,
}
```
6. Create an assets/icons folder and add all my svg files in it.

I get a 404 error on the request URL: http://localhost:3010/a9cee51ba4f45dedf5c1-TopLoggerIcons.woff

This used to work before I updated webfonts loader from 4.1.0 to 4.3.0 and nuxt from 1.4 to 2.3.4.
Any help or ideas is appreciated...

**Comment by KRaymundus** [comment]
Ok, just figured it does work if I use `embed: true`. So the styles are generated, its just the woff not being available somehow.

**Comment by KRaymundus** [comment]
Ok, got it working. The font is served from the /_nuxt directory, so you have to change the rule in `nuxt.config.js` to the following:

    extend(config, ctx) {
      config.module.rules.push({
        test: /plugins\/icons\.js$/,
        use: [
          'vue-style-loader',
          'css-loader',
          { 
            loader: 'webfonts-loader',
            options: {
              publicPath: config.output.publicPath,
            },
          }
        ],
      })
    }

**Comment by jeerbl** [comment]
Not on the roadmap for now but please feel free to make a pull request (the code is quite simple).

**Comment by xtoolkit** [comment]
hi
this solution work fine in > 2.14
but has error in v2.15
```
ERROR in ./plugins/icons.js (./node_modules/css-loader/dist/cjs.js!./node_modules/webfonts-loader??ref--12-2!./plugins/icons.js)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '/_nuxt/8bf71f6152eddc5786f7-gpicons-beta1.eot?#iefix' in '/home/arshen/dev/gapfilm/nuxt/plugins'
    at /home/arshen/dev/gapfilm/nuxt/node_modules/enhanced-resolve/lib/Resolver.js:209:21
    at /home/arshen/dev/gapfilm/nuxt/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/arshen/dev/gapfilm/nuxt/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /home/arshen/dev/gapfilm/nuxt/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /home/arshen/dev/gapfilm/nuxt/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/arshen/dev/gapfilm/nuxt/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /home/arshen/dev/gapfilm/nuxt/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/arshen/dev/gapfilm/nuxt/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at /home/arshen/dev/gapfilm/nuxt/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /home/arshen/dev/gapfilm/nuxt/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/arshen/dev/gapfilm/nuxt/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
    at /home/arshen/dev/gapfilm/nuxt/node_modules/enhanced-resolve/lib/RootPlugin.js:60:9
    at /home/arshen/dev/gapfilm/nuxt/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/arshen/dev/gapfilm/nuxt/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at /home/arshen/dev/gapfilm/nuxt/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /home/arshen/dev/gapfilm/nuxt/node_modules/enhanced-resolve/lib/Resolver.js:285:5
 @ ./plugins/icons.js 3:14-128
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./.nuxt/client.js
```

**Comment by merijnponzo** [comment]
Same problem, never had any problems untill i upgraded nuxt from 2.14 to 2.15.
And that is the story of my life.

```
odule build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '/_nuxt/ppcons.ppCons.351531e6981d4a9d7cfdf30345933534.eot?#iefix' in '/Applications/MAMP/htdocs/puppyplaza/frontend/plugins'
    at /Applications/MAMP/htdocs/puppyplaza/frontend/node_modules/enhanced-resolve/lib/Resolver.js:209:21
    at /Applications/MAMP/htdocs/puppyplaza/frontend/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Applications/MAMP/htdocs/puppyplaza/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Applications/MAMP/htdocs/puppyplaza/frontend/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /Applications/MAMP/htdocs/puppyplaza/frontend/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Applications/MAMP/htdocs/puppyplaza/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Applications/MAMP/htdocs/puppyplaza/frontend/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Applications/MAMP/htdocs/puppyplaza/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Applications/MAMP/htdocs/puppyplaza/frontend/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /Applications/MAMP/htdocs/puppyplaza/frontend/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Applications/MAMP/htdocs/puppyplaza/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Applications/MAMP/htdocs/puppyplaza/frontend/node_modules/enhanced-resolve/lib/RootPlugin.js:60:9
    at /Applications/MAMP/htdocs/puppyplaza/frontend/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Applications/MAMP/htdocs/puppyplaza/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Applications/MAMP/htdocs/puppyplaza/frontend/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /Applications/MAMP/htdocs/puppyplaza/frontend/node_modules/enhanced-resolve/lib/Resolver.js:285:5

 @ ./plugins/icons.js 11:14-230 24:4-30:6 25:23-239
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
```

**Comment by andreysuha2** [comment]
Same issue 

`Error: Can't resolve '/_nuxt/3260fdf705630fb546d7-IconFont.woff' in '/home/andrey/projects/zala/frontend/theme/plugins/IconFont'
    at /home/andrey/projects/zala/frontend/theme/node_modules/enhanced-resolve/lib/Resolver.js:209:21
    at /home/andrey/projects/zala/frontend/theme/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/andrey/projects/zala/frontend/theme/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/andrey/projects/zala/frontend/theme/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /home/andrey/projects/zala/frontend/theme/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/andrey/projects/zala/frontend/theme/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/andrey/projects/zala/frontend/theme/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/andrey/projects/zala/frontend/theme/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/andrey/projects/zala/frontend/theme/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /home/andrey/projects/zala/frontend/theme/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/andrey/projects/zala/frontend/theme/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/andrey/projects/zala/frontend/theme/node_modules/enhanced-resolve/lib/RootPlugin.js:60:9
    at /home/andrey/projects/zala/frontend/theme/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/andrey/projects/zala/frontend/theme/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/andrey/projects/zala/frontend/theme/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /home/andrey/projects/zala/frontend/theme/node_modules/enhanced-resolve/lib/Resolver.js:285:5
                                                                                                                                                    friendly-errors 15:00:27
 @ ./plugins/IconFont/index.js 3:14-134 16:4-22:6 17:23-143
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
`

**Comment by xtoolkit** [comment]
i change build option in nuxt.config file like this:

``` js
export default {
  build: {
    extend(config) {
      config.module.rules.push({
        test: /plugins\/icons\.js$/,
        use: [
          {
            loader: require.resolve('vue-style-loader'),
            options: this.buildContext.buildOptions.loaders.vueStyle
          },
          {
            loader: require.resolve('css-loader'),
            options: this.buildContext.buildOptions.loaders.css
          },
          {
            loader: require.resolve('webfonts-loader'),
            options: {
              publicPath: config.output.publicPath
            }
          }
        ]
      });
    }
  }
}
```

and fix for me
