### ISSUE TITLE
Hot update does not generate a new file?

### ISSUE THREAD

**Issue by jiechud** [jeerbl/webfonts-loader#6]
Can you add a configuration, I don't have to add a new detected `new.svg` files, webpack hot update won't be repackaged to generate new font

**Comment by jeerbl** [comment]
What is your Webpack version?

**Comment by jiechud** [comment]
webpack version  1.13.2 ，  To upgrade to 2.0?

**Comment by jeerbl** [comment]
Well I use Webpack 1.x and it works perfectly when I add a new icon to the folder.

**Comment by jeerbl** [comment]
Closing as not reproducible.
