### ISSUE TITLE
ttf2woff2@2.0.3 install  error

### ISSUE THREAD

**Issue by carey4756** [jeerbl/webfonts-loader#69]
when doing npm install webfonts-loader , What ttf2woff2@2.0.3 install  error it show

**Comment by jeerbl** [comment]
Hi @carey4756,

That'd be great to have more info, maybe a log of the install? (the part with the error).

Thanks,
Jerome

**Comment by carey4756** [comment]
Here is the error message: 
 gyp ERR! build error
    gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
    gyp ERR! System Windows_NT 6.1.7601
    gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
    gyp ERR! cwd F:\vue-boilerplate-template\node_modules\ttf2woff2
    gyp ERR! node -v v10.2.0
    gyp ERR! node-gyp -v v3.6.2
    gyp ERR! not ok

**Comment by carey4756** [comment]
What's wrong with npm install  ttf2woff2  inside of webfonts-generator package
