### ISSUE TITLE
extending generated class in sass files

### ISSUE THREAD

**Issue by nferruzzi** [jeerbl/webfonts-loader#7]
Hello,
I need your help, please :)
I've been trying to configure webpack 2 config file to generate the font.
So far I've a working webfont embedded but it doesn't work if I remove the embed query in the config file.
1) can we specify a destination path ? because 'dest' is ignored the path is always the root './....tff'
2) how to extend in sass files the generated webfont and classes 

please..
thank you in advance

**Comment by nferruzzi** [comment]
'dest' is still ignored but if I change the publicPath it works

`new webpack.LoaderOptionsPlugin({ test: /\.js$/, options: { output: { publicPath: '/static/' } } })`

Please I still need help with point 2

**Comment by jeerbl** [comment]
Could you try with version 1.0.0? Maybe it fixes this.

**Comment by jeerbl** [comment]
Closing this as not reproducible

**Comment by krayushfk** [comment]
@jeerbl Any update on point 2?

How to extend in sass files the generated webfont and classes
