### ISSUE TITLE
Doesn't work with webpack ^4.19.1

### ISSUE THREAD

**Issue by bazilyuk** [jeerbl/webfonts-loader#70]
webpack.config.js file:
`      {
        test: /\.font\.js/,
        use: [MiniCssExtractPlugin.loader, 'css-loader', 'webfonts-loader'],
      },`
myfont.font.js file:
`module.exports = {
  files: ['../src/common/markup/common/icons/bag.svg'],
  dest: '../src/common/markup/common/fonts/',
  css: true,
  fontName: 'ico',
  cssDest: '../src/common/markup/common/scss/ico/_ico-complete.scss',
  cssFontsUrl: '/fonts',
  templateOptions: {
    baseSelector: '.ico',
    classPrefix: 'ico-',
  },
  cssTemplate: '../src/common/markup/common/scss/ico/_ico-template.hbs',
  startCodepoint: Number('0xe001'),
  normalize: true,
  fontHeight: '200',
};
`
after build nothing happen and show error, that icons files are not includes and scss variables too

**Comment by Canic** [comment]
try to give a absolute path not a relative!
Can not reproduce a problem on my Project!

**Comment by jeerbl** [comment]
Closing cause of inactivity
