### ISSUE TITLE
cssDest has no affect on the generated css/scss file

### ISSUE THREAD

**Issue by michaeldietiker** [jeerbl/webfonts-loader#72]
Hi @jeerbl 

My goal is to generate the scss file to a different directory and rename it to _icons.scss. I'm trying to achieve this with cssDest as described [here](https://github.com/sunflowerdeath/webfonts-generator#cssdest), but the scss file stays in the same directory and keeps the same name as the webfonts do. I also tried this with scssFile: false, but the behaviour with css is the same. My webpack config is as followed:

package.json:
```
{
  "name": "Webfonts-Loader-Test",
  "license": "MIT",
  "dependencies": {
    "css-loader": "*",
    "mini-css-extract-plugin": "^0.7.0",
    "webfonts-loader": "^4.4.0",
    "webpack": "*",
    "webpack-cli": "^3.3.1",
    "webpack-merge": "*"
  }
}
```

webpack.config.js:
```
const path = require('path');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
    entry: [
        './entry.js'
    ],
    output: {
        path: path.resolve(__dirname, 'dist'),
        publicPath: '/',
        filename: 'bundle.js'
    },
    module: {
        rules: [
            {
                test: /\icons\.js$/,
                use: [
                    MiniCssExtractPlugin.loader,
                    'css-loader',
                    'webfonts-loader'
                ]
            }
        ]
    },
    plugins: [
        new MiniCssExtractPlugin({
            filename: 'styles.css'
        })
    ]
};
```

icons.js:
```
module.exports = {
    files: [
        './icons/*.svg'
    ],
    fontName: 'Icons',
    classPrefix: 'icon-',
    baseSelector: '.icon',
    embed: true,
    scssFile: true,
    writeFiles: true,
    types: ['woff2', 'ttf'],
    dest: './dist/fonts/',
    cssFontsUrl: '/dist/fonts/',
    cssDest: './dist/scss/_icons.scss'
};
```

Any ideas on how to achieve this?

Cheers,
Michael

**Comment by michaeldietiker** [comment]
@jeerbl any ideas? :)

**Comment by GilbertoTomasone** [comment]
Hi @jeerbl and @michaeldietiker 

I have stumbled on the same issue and I found out that the cssDest option is not included in the list of the generatorOptions defined by the loader.

Any chance you can extend the generatorOptions to include the cssDest, please?

Thanks,

Gilberto

**Comment by michaeldietiker** [comment]
Thanks heaps @GilbertoTomasone!

**Comment by michaeldietiker** [comment]
Hi @GilbertoTomasone

I checked your pull request and updated the cssDest option in #89

The path will be generated dynamically now.

Cheers,
Michael

**Comment by jeerbl** [comment]
Thanks guys! Will be released in next version.

**Comment by michaeldietiker** [comment]
No worries. Thanks for merging!
