### ISSUE TITLE
How to generate variables for icon codecs?

### ISSUE THREAD

**Issue by devalexqt** [jeerbl/webfonts-loader#86]
I need to use fonticon in css pseudo elements, now I specify character code like so:
```
    a:before{
        font-family: 'fonticons';
        content: "\f102"; / * this code for 1.svg */
        color:red;
    }
```
But if I add new svg to my icon font build when character code can be changed (if new svg file change folder structure), and on page will be displayed wrong icon!   
How to fix this?

**Comment by DamianOsipiuk** [comment]
Use `codepoints`

Ex.
```
codepoints: {
    settings: 0xe001,
  },
```
This will generate stable identifier for the `settings.svg`
