### ISSUE TITLE
Add a note about usage alongside with other rules for .js files

### ISSUE THREAD

**Issue by the-owl** [jeerbl/webfonts-loader#91]
I've run into a strange error in MiniCssExtractPlugin when I tried to use `webfonts-loader` in a vue-cli@4 production build:
```
 error  in ./src/fonts/icons.font.js

Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 1)
Cannot read property 'outputOptions' of undefined
    at PoolWorker.fromErrorObj (.../frontend/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at .../frontend/node_modules/thread-loader/dist/WorkerPool.js:204:29
    at Object.pitch (.../frontend/node_modules/mini-css-extract-plugin/dist/loader.js:83:294)

 @ multi ./src/main.ts ./src/fonts/icons.font.js
```

After some debugging I found out that error is caused by conflict with loaders defined for `.js` files. vue-cli applies thread-loader before babel/ts to speed up builds, and defines that .js rule before user-defined rule for webfonts-loader. As result, loaders are applied in invalid order:
```
thread-loader
babel-loader
MiniCssExtractPlugin.loader
css-loader
webfonts-loader
```

It turned out that solution is already described in this comment: https://github.com/jeerbl/webfonts-loader/issues/66#issuecomment-526848952
Other possible solutions are:
1. place webfonts-loader rule before generic .js rule (not quite straightforward with vue.config.js)
2. change `.font.js` to any other extension without `.js` in the end, e.g. `.iconfont`

I think that it would be great to add a note to README about vue-cli setup and possibility of such conflicts with other complex setups, and describe how to solve them, just to save time for users who face similar issues.

**Comment by jeerbl** [comment]
Hi @the-owl,

I don't understand this issue very much. The point of having a `.font.js` name is to be able to define loaders specifically for the font file. What exactly is the issue here?

Jerome

**Comment by the-owl** [comment]
The problem is that Vue standard build setup (via vue-cli) defines its own set of webpack loaders for `*.js` files. One of these loaders is `thread-loader`. As a result, files with `*.font.js` names are also handled with `thread-loader` which breaks `webfonts-loader`. It may take a lot of time to figure out a root cause of the problem, so I suggest adding a note about this for Vue users to readme.

**Comment by jeerbl** [comment]
Hi @the-owl, can you add that with a pull request? Thx :)

**Comment by jeerbl** [comment]
Closed as inactive
