### ISSUE TITLE
Duplicate fonts in svg

### ISSUE THREAD

**Issue by webjohan** [jeerbl/webfonts-loader#94]
When updating from version 4.4.0 to 5.1.1 (any version 5) I get duplicate icons in svg font.
example

icon-one
icon-one-1

**Comment by webjohan** [comment]
<glyph glyph-name="icon"
      unicode="&#xF165;"
<glyph glyph-name="icon-1"
      unicode="&#x6F;&#x72;&#x67;&#x61;&#x6E;&#x69;&#x7A;&#x61;&#x74;&#x69;&#x6F;&#x6E;"

Making the svg-font file almost twice as big as it should be

**Comment by NathanMigomFrucon** [comment]
I have the same with all versions except for version 5.3.0. Newer versions after this one seem to have this issue again also.
