### ISSUE TITLE
Expose webfonts-generator ligature option

### ISSUE THREAD

**Issue by andersk** [jeerbl/webfonts-loader#98]
`webfonts-generator` has a [`ligature` option](https://github.com/vusion/webfonts-generator#ligature) to disable generation of ligatures from the input filenames, but it does not seem to be possible to configure this from `webfonts-loader`. This would be useful to work around a [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1634834) with long ligatures, and also to produce smaller files.

**Comment by jeerbl** [comment]
I added the `ligature` option in v5.3.0.

**Comment by andersk** [comment]
Thanks!

You may have unintentionally changed the default too, since  `undefined` will overwrite the default value in the `_.extend({}, DEFAULT_OPTIONS, options)` call used by `webfonts-generator`. Defaulting to `false` may actually be fine, since I expect typical users probably reference the Unicode private-use codepoints via the CSS template rather than using the ligatures. But I figured you might want to be aware.

**Comment by jeerbl** [comment]
Well the `ligature` param in `webfonts-generator` defaults to `true` so this will default to that default value. I updated the code in v6.0.1.
